---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# simpleHM

<!-- badges: start -->
<!-- badges: end -->

The goal of simpleHM is to provide as simple yet modular approach to create heatmap visualisations.

## Installation

You can install the development version of simpleHM like so:

``` r
# install.packages("devtools")
devtools::install_github("jennybc/regexcite")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(simpleHM)
df <- data.frame(samples = c(paste0("untreated", 1:6), paste0("treated", 7:12)),
                 group = c(rep("Untreated",6), rep("Treated",6)),
                 patient = c(rep(paste0("Patient", 1:3), 4)),
                 var1 = c(rnorm(6, 10, 1),  rnorm(6, 7, .7)),
                 var2 = c(rnorm(6, 10, 1),  rnorm(6, 200, 10)),
                 var3 = c(rnorm(6, 50, 5),  rnorm(6, 10, 1)),
                 var4 = c(rnorm(6, 10, 1),  rnorm(6, 60, .7)))

heatmap_plot <- simpleHM(df)    
heatmap_plot
```


